### ISSUE TITLE
ToDo: Check for .mp3 files in resource directory

### ISSUE THREAD

**Issue by jasonwynn10** [LostTeam/LostSounds#3]

**Comment by TylerGames** [comment]
Interesting.

**Comment by MCUnderground** [comment]
@jasonwynn10 so will it work? Hmmm

**Comment by jasonwynn10** [comment]
@MCUnderground Possibly. I need to look a few things up to know for sure though.

**Comment by MCUnderground** [comment]
@jasonwynn10 i dont think it has.

**Comment by MCUnderground** [comment]
Wait it mighy have.... It reads mcpe sounds. Which may be in odd(i think thtas extension) or mp3

**Comment by jasonwynn10** [comment]
in the pocketmine-mp.phar file, there are mp3 files present...

**Comment by ImagicalGamer** [comment]
^^ Cool, it could possible be done.
