### ISSUE TITLE
Sending sounds through packet data

### ISSUE THREAD

**Issue by jasonwynn10** [LostTeam/LostSounds#5]
I am going to learn how to send specialized packets of data to have the sound play on the user's devices. does anyone already know how to do this?

**Comment by TheDeibo** [comment]
Check this out. https://forums.pocketmine.net/threads/how-to-use-addsound.8353/

**Comment by jasonwynn10** [comment]
thanks, but it still doesn't help for sending sounds that aren't already on the players device or implemented in the game
